### ISSUE TITLE
修改，发布文章显示500，api未配置，实际已经修改成功

### ISSUE THREAD

**Issue by xhpk** [wehaox/Typecho-Butterfly#17]
写新文章，或者修改会显示api未配置，但是实际上已经修改成功了
![image](https://user-images.githubusercontent.com/40262993/179380466-991b86f0-24c0-4b02-81c8-71bfdb76c3a9.png)

另外请教下，我的文章之前设置了略缩图，切换主题之后，需要重新设置，请问在哪里可以批量修改该字段。谢谢！

**Comment by wehaox** [comment]
api未配置应该和主题无关，你看看是不是什么插件的问题
文章缩略图在编辑文章时，下面的自定义字段第一个就是设置缩略图的

**Comment by xhpk** [comment]
> api未配置应该和主题无关，你看看是不是什么插件的问题 文章缩略图在编辑文章时，下面的自定义字段第一个就是设置缩略图的

ok，搞定，插件冲突，谢谢
