### ISSUE TITLE
手机端夜间模式下文章目录没有变色

### ISSUE THREAD

**Issue by fukoy** [wehaox/Typecho-Butterfly#18]
手机端夜间模式下文章目录没有变色
![FEDBEE86-0717-4C75-88C2-74046A1C0D74](https://user-images.githubusercontent.com/11289325/179439794-7dfcbeee-f84d-4f8f-b620-1c279785a22a.png)

**Comment by wehaox** [comment]
感谢反馈，下版本修复

**Comment by wehaox** [comment]
1.6.0已修复
