### ISSUE TITLE
控制台输出错误

### ISSUE THREAD

**Issue by misaka10032w** [wehaox/Typecho-Butterfly#20]
控制台会输出`GET http://******.***/index.php/archives/3/0 net::ERR_ABORTED 404 (Not Found)`
请求的是`<script src="0" type="text/javascript"></script>`
尝试找了一下似乎和footer.php的96行
`<?php $this->header('commentReply=1&description=0&keywords=0&generator=0&template=0&pingback=0&xmlrpc=0&wlw=0&rss2=0&rss1=0&antiSpam=0&atom'); ?>`
有关，注释掉就没了，本人半吊子，不太明白发生了啥，求解，谢谢

**Comment by wehaox** [comment]
96行是用来解决开启pjax无法评论的，控制台报错不会对博客产生影响可以忽略

**Comment by misaka10032w** [comment]
就是如果不需要pjax，注释掉也没有问题呗，明白了，谢谢啦
