### ISSUE TITLE
文章页面和独立页面的头图在后台没有设置项

### ISSUE THREAD

**Issue by BFDZ** [wehaox/Typecho-Butterfly#24]
博客安装以后，文章页面头部背景图是一个蓝底的图片，后台好像没有地方可以设置 `background-image:` 这个参数，我直接改了 ` /page_header.php` 里面的url图片链接才改成功，这个功能应该和首页背景图一样加个自定义图片链接的设置项。

![](https://tva1.sinaimg.cn/large/007DpwBhgy1h5cz7nm7kjj30ky0din25.jpg)

**Comment by wehaox** [comment]
在编辑文章或者独立页面时，往下翻找到 `自定义字段`里的 `自定义文章缩略图`，这里是设置顶图的
