### ISSUE TITLE
[issue][1.6.0]评论区头像样式

### ISSUE THREAD

**Issue by XenWayne** [wehaox/Typecho-Butterfly#25]
![image](https://user-images.githubusercontent.com/54123699/187809653-e12e3d0d-10d3-486a-a37f-6b21d2324417.png)
![image](https://user-images.githubusercontent.com/54123699/187809714-e9b86440-dcb5-4ed9-96da-93308541d059.png)
图二1.5.0
如图 这个头像这么大是忘了加width还是特殊的设计（

**Comment by wehaox** [comment]
header_com.php里25行的style.css后面版本号随便改成别的就好了
