### ISSUE TITLE
文章缩略图全都不显示了

### ISSUE THREAD

**Issue by dxs1256** [wehaox/Typecho-Butterfly#26]
Typecho版本 1.2.0。文章缩略图和作者头像全都不显示了。主页顶图(banner image)可以正常显示。打开文章顶图又可以正常显示。请教一下怎么回事呀

**Comment by yzl3014** [comment]
同问QAQ

**Comment by BFDZ** [comment]
我也是，图像也不显示了

**Comment by wehaox** [comment]
我无法复现你出现的问题，能否将博客地址发给我看看。
可能是对主题进行过修改导致的，你可以尝试先对原来的主题文件备份，然后全新安装看看是否有同样问题。

**Comment by dxs1256** [comment]
设置外观里“jsdelivr提供的cdn源切换(默认采用gcore源)”换一个就好了

**Comment by BFDZ** [comment]
CDN源我用的是本地加载，1.6.3没有发布static文件包

**Comment by wehaox** [comment]
> CDN源我用的是本地加载，1.6.3没有发布static文件包

没有就是和上个版本一样
