### ISSUE TITLE
演示站点的标签二级下拉菜单是怎么设置的

### ISSUE THREAD

**Issue by Arturia169** [wehaox/Typecho-Butterfly#28]
***
#如图所示
> ![image](https://user-images.githubusercontent.com/69199123/198200860-8cddac3c-07ac-4ea1-b07f-637e86f73305.png)
***
#我自己的站点只有一级菜单
> ![image](https://user-images.githubusercontent.com/69199123/198201021-6d3a9453-75e6-48e8-9f84-f0dd32ab95f9.png)

**Comment by wehaox** [comment]
看主题使用文档
