### ISSUE TITLE
在分类、标签、搜索页面中首页轮播图仍然显示

### ISSUE THREAD

**Issue by yzl3014** [wehaox/Typecho-Butterfly#31]
如标题所述。在博客域名下的“/search/”、“/category/”、“/tag/”页面里，主页轮播图仍然会在背景图（会在上层会显示“标签 Blog 下的文章”之类字样的头图）的下方显示。
希望能加入轮播图 在非首页显示 的开关，以便减少视觉干扰；觉得必要时，站长还可以再次打开以吸引访客点击。

**Comment by wehaox** [comment]
好的，下版本更新
