### ISSUE TITLE
主题设置里 顶部菜单栏 折叠后无法恢复

### ISSUE THREAD

**Issue by yzl3014** [wehaox/Typecho-Butterfly#33]
如问题所述。当我在/admin/options-theme.php中，单击悬浮在页面顶端的菜单中的任一链接后，正常跳转，但是菜单栏无法再展开（如下图所示）。希望能解决。
![菜单无法展开](https://user-images.githubusercontent.com/79385954/200885254-08c9de85-a80d-4f98-8586-49cfa4276bad.png)

**Comment by wehaox** [comment]
我这边是可以正常展开的，你看看f12控制台是否有报错

**Comment by yzl3014** [comment]
我以为菜单栏会在页面回到顶部时自动展开，没想到还需要单击一下才行。
实际上是没有无法展开的BUG的，问题算是解决了。
