### ISSUE TITLE
希望能加上 友链下方备注 功能

### ISSUE THREAD

**Issue by yzl3014** [wehaox/Typecho-Butterfly#34]
如建议所述。大多数博客申请友链都有要求，但限于主题没有此功能且Typecho最新版尚不支持评论置顶。希望能添加友链下方备注功能（就是在友情链接下方附上一些要求，如https://yuanzj.top/Links.html 所示，亦可看附图2）以解决此问题。
经本人简单开发测试（代码页面如图1）并使用了一段时间后，发现码html代码不如写Markdown方便，最佳解决方式即单独添加一个Typecho页面模板，以此作为备注功能的“编辑器”。
![图1-友链申请备注功能设置](https://user-images.githubusercontent.com/79385954/200893742-a23b144b-a01a-418b-b16e-e765fc54ba1b.png)
![图二-本人简单开发的“友链下方备注”功能](https://user-images.githubusercontent.com/79385954/200895823-70831873-d25c-49ca-aa9e-c0917c90eb69.png)

**Comment by wehaox** [comment]
测试了下，友链模块似乎有bug，之后会更新

**Comment by wehaox** [comment]
新版已发布

**Comment by yzl3014** [comment]
> 新版已发布

在今天这个版本把问题修复之前，备注功能都靠我手撸html和php，还要考虑到新版本覆盖😂
这下终于可以轻松了😜
