### ISSUE TITLE
已发现的问题汇总

### ISSUE THREAD

**Issue by etetc** [wehaox/Typecho-Butterfly#37]
主题高大尚，为您点赞。使用中有以下问题，请查证：

1.置顶文章出错：Database Query Error
情况：Typecho 版本 1.1 (17.10.30)/SQLite,主题版本: 1.7.0;输入置顶文章的 cid,首页出错：Database Query Error，其它页面（分类页内容页）均正常显示。

2."是否显示文章内相关推荐"功能无效。即关闭情况下，内容页还显示（测试环境如上）。

3.内容页不显示标题,发表日期等信息
情况：在美化选项->是否显示文章示顶图,关闭情况下，不显示标题、发表日期等内容；
建议：优化为：在文章示顶图时，显示标题、发表日期等标题信息。

4.显示最新文章,开启情况下：侧栏“最新文章”，好像没有数量限制。
建议：在后台可以输入具体数量，对应在前端侧栏显示。

**Comment by wehaox** [comment]
感谢反馈
1.开发环境没有测试过sqlite，推荐使用mysql，后期我会尝试测试sqllite
2.确实是bug，下版本修复
3.测试了下，是显示的，请提供下你的截图看看
4.侧栏显示数量设置是typecho提供的设置，在设置 > 阅读中

**Comment by etetc** [comment]
好的。
3, 不同的设置及对应的前端显示如下： 
https://github.com/etetc/web/blob/main/test-1.jpg

https://github.com/etetc/web/blob/main/test-2.jpg

**Comment by wehaox** [comment]
> 好的。 3, 不同的设置及对应的前端显示如下： https://github.com/etetc/web/blob/main/test-1.jpg
> 
> https://github.com/etetc/web/blob/main/test-2.jpg

404

**Comment by etetc** [comment]
https://etetc.github.io/temp/test-1.jpg
https://etetc.github.io/temp/test-2.jpg

**Comment by wehaox** [comment]
> https://etetc.github.io/temp/test-1.jpg https://etetc.github.io/temp/test-2.jpg

这个问题我在sqlite下无法复现

置顶的bug将在下版本修复
