### ISSUE TITLE
水平分割线组件上的小剪刀图标不时抽风

### ISSUE THREAD

**Issue by yzl3014** [wehaox/Typecho-Butterfly#39]
如题所述。在网站中的水平分割线上（`<hr>`标签）会显示一个剪刀图标，正常情况下，鼠标悬浮于虚线上，剪刀从左侧的初始位置移到右侧，鼠标离开就返回。
问题出现在，当鼠标**直接放在**剪刀图标上的某个位置（位置不固定）时，**有一定几率**（可能是虚线越短几率越大）出现如下方GIF图（共13秒）所示的“抽风”情况。
![GIF动图演示](https://user-images.githubusercontent.com/79385954/203716643-58fa35bf-0664-46d7-8859-f20be5ea8729.gif)
本站主题版本为两天前（即2022年11月22日）发布的1.7.1版本，通过Release覆盖更新。但该问题在之前的版本也出现过。

**Comment by wehaox** [comment]
正常现象，原版主题也是这样，无伤大雅
