### ISSUE TITLE
设置置顶文章博客报错无法打开: database query error

### ISSUE THREAD

**Issue by Dev-Wiki** [wehaox/Typecho-Butterfly#42]
这是只设置轮播, 博客正常.
![image](https://user-images.githubusercontent.com/12946956/205471581-7b9ccdeb-506d-49be-8680-3668adeb225e.png)

如果设置了置顶
![image](https://user-images.githubusercontent.com/12946956/205471600-4a57131b-23d4-4e83-96fc-69947bb25a56.png)
设置后刷新首页
![image](https://user-images.githubusercontent.com/12946956/205471607-ff34a796-a037-4239-983c-8b59f89f3945.png)

**Comment by wehaox** [comment]
使用空格分隔试试

**Comment by Dev-Wiki** [comment]
> 使用空格分隔试试

设置单个 置顶也要加空格么?

**Comment by wehaox** [comment]
> > 使用空格分隔试试
> 
> 设置单个 置顶也要加空格么?

单个不用加，多个用空格分开

**Comment by Dev-Wiki** [comment]
> > > 使用空格分隔试试
> > 
> > 
> > 设置单个 置顶也要加空格么?
> 
> 单个不用加，多个用空格分开

就是设置了单个置顶

**Comment by wehaox** [comment]
> 是从 release下载的, docker运行, 威联通的nas
> 
> > 还有你的运行环境

数据库是sqlite吗

**Comment by Dev-Wiki** [comment]
> > 是从 release下载的, docker运行, 威联通的nas
> > > 还有你的运行环境
> 
> 数据库是sqlite吗

是的

**Comment by wehaox** [comment]
> > > 是从 release下载的, docker运行, 威联通的nas
> > > > 还有你的运行环境
> > 
> > 
> > 数据库是sqlite吗
> 
> 是的, typecho 1.2 docker版本

此问题确实是sqlite的问题，已有相同的issue #37 ，我之后会尝试测试sqlite数据库
