### ISSUE TITLE
js加载错误导致首页显示空白

### ISSUE THREAD

**Issue by Dev-Wiki** [wehaox/Typecho-Butterfly#44]
如图所示:
![image](https://user-images.githubusercontent.com/12946956/205471803-60aa0e1b-d023-4ddf-af1c-9a492430edc2.png)

![image](https://user-images.githubusercontent.com/12946956/205471806-ec88cd6c-9456-47b7-bf17-3161874ca4e7.png)

![image](https://user-images.githubusercontent.com/12946956/205471811-804009d3-4120-48dd-8030-b2f577639913.png)

**Comment by wehaox** [comment]
新版本已发布

**Comment by Dev-Wiki** [comment]
这个还是存在 最新的 sqlite 版本

**Comment by wehaox** [comment]
> 这个还是存在 最新的 sqlite 版本
要申请key才行

**Comment by Dev-Wiki** [comment]
> > 这个还是存在 最新的 sqlite 版本
> > 要申请key才行

申请什么key? 
![image](https://user-images.githubusercontent.com/12946956/209928516-745ddcbb-e07c-4b04-bc0f-670b437f50c1.png)

**Comment by wehaox** [comment]
> > > 这个还是存在 最新的 sqlite 版本
> > > 要申请key才行
> 
> 申请什么key? ![image](https://user-images.githubusercontent.com/12946956/209928516-745ddcbb-e07c-4b04-bc0f-670b437f50c1.png)

主题设置里有填和风天气和高德的key

**Comment by Dev-Wiki** [comment]
> 

懂了, 如果不填写 是不是可以隐藏.

**Comment by wehaox** [comment]
> > 
> 
> 懂了, 如果不填写 是不是可以隐藏.

不填就给侧栏里的时钟勾选去掉

**Comment by Dev-Wiki** [comment]
> > > 
> > 
> > 
> > 懂了, 如果不填写 是不是可以隐藏.
> 
> 不填就给侧栏里的时钟勾选去掉

非常感谢, 看设置的时候没觉得这两个有必然联系.
![image](https://user-images.githubusercontent.com/12946956/209931658-ebbfef4f-7651-497a-8e2f-2801e072eb03.png)


感谢耐心回答, 非常感谢~
