### ISSUE TITLE
[Bug]: html无法正常显示

### ISSUE THREAD

**Issue by yunuoyumeng** [wehaox/Typecho-Butterfly#45]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.3

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Chrome

### 博客的运行环境？ | What the running environment of the blog?

linux|php7.2+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

使用!!!html代码!!!
html代码多起来无法正常显示

**Comment by wehaox** [comment]
提供下截图

**Comment by wehaox** [comment]
提供下截图

**Comment by yunuoyumeng** [comment]
> 提供下截图

https://c2.im5i.com/2023/01/24/YTq16.jpeg

**Comment by wehaox** [comment]
> > 提供下截图
> 
> https://c2.im5i.com/2023/01/24/YTq16.jpeg

代码是什么

**Comment by yunuoyumeng** [comment]
> > > 提供下截图
> > 
> > 
> > https://c2.im5i.com/2023/01/24/YTq16.jpeg
> 
> 代码是什么
删一大半才能正常显示
!!!
<!doctype html>
<html lang="zh-cmn-Hans">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no"/>
    <meta name="renderer" content="webkit"/>
    <meta name="force-rendering" content="webkit"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    
    <link rel="stylesheet" href="https://unpkg.com/mdui@1.0.2/dist/css/mdui.min.css"/>
  </head>
  <body>
  <div class="mdui-tab" mdui-tab>
  <a href="#ACG" class="mdui-tab-active mdui-ripple">
    <i class="mdui-icon material-icons">thumb_up</i>
    <label>ACG区</label>
  </a>
  <a href="#Minecraft" class="mdui-ripple">
    <i class="mdui-icon material-icons">games</i>
    <label>MC区</label>
  </a>
  <a href="#resources" class="mdui-ripple">
    <i class="mdui-icon material-icons">folder</i>
    <label>资源区</label>
  </a>
  <a href="#tool" class="mdui-ripple">
    <i class="mdui-icon material-icons">build</i>
    <label>工具区</label>
  </a>
</div>

<div id="ACG"
<ul class="mdui-list">
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://p1.bdxiguaimg.com/origin/pgc-image/8069753dcbde447aa5eacf1bf3f390b5"/>
    </div>
    <div class="mdui-list-item-content">AGE动漫</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">在线动画，动漫下载</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://www.agemys.net';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://www.xmfans.me/yxsf/yh_pic/ico.png"/>
    </div>
    <div class="mdui-list-item-content">樱花动漫</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">专注动漫的门户网站</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://yhdmp.net';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="http://www.zzzfun.com/template/JOELEO/asset/img/favicon.ico"/>
    </div>
    <div class="mdui-list-item-content">ZzzFun动漫</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">配合上面两个用</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='http://www.zzzfun.com';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://bangumi.tv/img/favicon.ico"/>
    </div>
    <div class="mdui-list-item-content">Bangumi 番组计划</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">ACG百科</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://bangumi.tv';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2022/07/13/jR5qV1.jpg"/>
    </div>
    <div class="mdui-list-item-content">Animex动漫社</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">二次元及日本文化速报</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='http://www.animetox.com';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://air.tls.moe/favicon.ico"/>
    </div>
    <div class="mdui-list-item-content">airAnime</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">聚合番剧搜索工具</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://air.tls.moe';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://toolb.cn/favicon/acgdh.cc"/>
    </div>
    <div class="mdui-list-item-content">ACG导航</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">一个很不错的导航站</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://acgdh.cc';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
</ul>
</div>

<div id="Minecraft"
<ul class="mdui-list">
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
</ul>
</div>

<div id="resources"
<ul class="mdui-list">
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
</ul>
</div>

<div id="tool"
<ul class="mdui-list">
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
  <li class="mdui-list-item mdui-ripple">
    <div class="mdui-list-item-avatar">
      <img src="https://s1.ax1x.com/2023/01/23/pSJ7O6P.jpg"/>
    </div>
    <div class="mdui-list-item-content">待添加</div>
    <div class="mdui-list-item-text mdui-list-item-one-line"><span class="mdui-text-color-theme-text">敬请期待</div>
    <i class="mdui-list-item-icon mdui-icon material-icons"onclick="window.location.href='https://arcxingye.github.io/r18/';">link</i>
    <li class="mdui-divider-inset mdui-m-y-0"></li>
  </li>
</ul>
</div>

    
    <script src="https://unpkg.com/mdui@1.0.2/dist/js/mdui.min.js"></script>
  </body>
</html>
!!!

**Comment by yunuoyumeng** [comment]
> > > 提供下截图
> > 
> > 
> > https://c2.im5i.com/2023/01/24/YTq16.jpeg
> 
> 代码是什么

草率了，这是我插入的html https://yunpan.moe/s/lxyiQ

**Comment by wehaox** [comment]
> > > > 提供下截图
> > > 
> > > 
> > > https://c2.im5i.com/2023/01/24/YTq16.jpeg
> > 
> > 
> > 代码是什么
> 
> 草率了，这是我插入的html https://yunpan.moe/s/lxyiQ

是bug，年后再修

**Comment by wehaox** [comment]
新版已修复了插入html不显示问题，但是由于引入其他框架样式不兼容问题不会被修复
