### ISSUE TITLE
[Bug]: 1.7.3文章略缩图和头像无法显示

### ISSUE THREAD

**Issue by xhpk** [wehaox/Typecho-Butterfly#46]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.3

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Chrome

### 博客的运行环境？ | What the running environment of the blog?

linux|php7.2+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

如图，1.7.2版本无此问题，另：祝新年快乐
![image](https://user-images.githubusercontent.com/40262993/214803599-ff579d42-725b-4b1e-92f3-75e4f60dacfa.png)

**Comment by wehaox** [comment]
解压的时候可能没有完全覆盖主题文件
