### ISSUE TITLE
[Bug]: 文章页公告无法关闭

### ISSUE THREAD

**Issue by wyj5211** [wehaox/Typecho-Butterfly#47]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.3

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Chrome

### 博客的运行环境？ | What the running environment of the blog?

linux|php8.0+|typecho1.2|sqlite|nginx

### 问题描述 | Describe the bug

typecho用的是1.2 [开发版](https://github.com/typecho/typecho/commit/bad3ef651d23154e6acc525bc193111dcda557c8)
在后台已关闭侧边栏显示公告，文章页的侧边栏显示也全部关闭，可在文章页还是能看见公告，但在主页就没有  
[这是我的文章页](https://blog.wyj5211.me/archives/termux-usb.html)     [这是主页](https://blog.wyj5211.me/)  
另附后台设置截图  
![27-1-2023-11483-blog-wyj5211-me.jpg](https://i.postimg.cc/xdcbnp5L/27-1-2023-11483-blog-wyj5211-me.jpg)  
文章页截图  
![27-1-2023-114624-blog-wyj5211-me.jpg](https://i.postimg.cc/Wb3JVWF9/27-1-2023-114624-blog-wyj5211-me.jpg)

**Comment by wyj5211** [comment]
还有文章侧栏设置那里 显示网站**咨询** 打错字了

**Comment by wyj5211** [comment]
还有文章侧边栏显示设置那里 显示网站咨询 打错字了

**Comment by wehaox** [comment]
在post_sidebar.php中，公告部分添加php判断

<?php if (!empty($this->options->sidebarBlock) && in_array('ShowAnnounce', $this->options->sidebarBlock)): ?> 
    <div class="card-widget card-announcement"><div class="item-headline">
        <i class="fas fa-bullhorn card-announcement-animation"></i><span>公告</span></div>
    <div class="announcement_content"><?php $this->options->announcement() ?></div></div>
<?php endif; ?>

**Comment by wyj5211** [comment]
> 在post_sidebar.php中，公告部分添加php判断
> 
> ```
> <?php if (!empty($this->options->sidebarBlock) && in_array('ShowAnnounce', $this->options->sidebarBlock)): ?> 
>     <div class="card-widget card-announcement"><div class="item-headline">
>         <i class="fas fa-bullhorn card-announcement-animation"></i><span>公告</span></div>
>     <div class="announcement_content"><?php $this->options->announcement() ?></div></div>
> <?php endif; ?>
> ```

测试成功
