### ISSUE TITLE
[issue]关于站点标题获取

### ISSUE THREAD

**Issue by XenWayne** [wehaox/Typecho-Butterfly#5]
header.php  line9
主标题为什么获取的是description？
```php
<h1 id="site-title"><?php $this->options->description() ?></h1>
```
获取的不应该是标题么= =
$this->options->title();

表示疑惑.jpg

**Comment by wehaox** [comment]
typecho基本设置提供了 站点名称 和 站点描述 
$this->options->title();已经放在左上角了
这里就放描述了
