### ISSUE TITLE
[Bug]: 首页第一篇文章无法正常进入，如果进入就变成500报错

### ISSUE THREAD

**Issue by aicgfun** [wehaox/Typecho-Butterfly#50]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.3

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Chrome

### 博客的运行环境？ | What the running environment of the blog?

linux|php7.2+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

![Screenshot_20230218_022855](https://user-images.githubusercontent.com/105501633/219751827-10645c87-55e4-46d9-8b14-1dba63f331f8.png)

**Comment by wehaox** [comment]
非主题文件报错，无法定位问题，你可以尝试切换主题看看是否存在同样报错，还有插件是否冲突
