### ISSUE TITLE
[Bug]: 手机侧边栏标签、分类点进去404

### ISSUE THREAD

**Issue by aicgfun** [wehaox/Typecho-Butterfly#51]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.3

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Chrome

### 博客的运行环境？ | What the running environment of the blog?

linux|php7.2+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

![Screenshot_2023_0218_023213](https://user-images.githubusercontent.com/105501633/219753021-2bd81382-31fb-430a-aaaa-b2f0d958596a.png)
![Screenshot_2023_0218_023223](https://user-images.githubusercontent.com/105501633/219753094-715db1ae-bc39-45c8-be81-a98a4c0c98d8.png)

**Comment by wehaox** [comment]
去主题设置填入标签和分类的地址
