### ISSUE TITLE
文章列表封面可以支持去掉封面吗？

### ISSUE THREAD

**Issue by Ackerven** [wehaox/Typecho-Butterfly#53]
为文章选头图是一件令人头疼的事情，我仔细查找了设置里面，只有以下三个选项
![image](https://user-images.githubusercontent.com/70303900/222909442-4df6408d-e15c-4591-b7f5-b409281bbdd5.png)
求一个去掉封面的功能，Orz

**Comment by wehaox** [comment]
未来会安排

**Comment by kifuan** [comment]
@Ackerven 目前可以自行编辑 `index.php` 注释掉以下代码或者直接删掉

https://github.com/wehaox/Typecho-Butterfly/blob/6bcfe9030f10e3cf8e55ff688eb1d2b3c6c4d51b/index.php#L49-L52

**Comment by wehaox** [comment]
新版本已更新
