### ISSUE TITLE
编辑页里预览主题报错（Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /www/wwwroot/typecho.mgcl2.ml/var/Widget/Base/Contents.php on line 938）

### ISSUE THREAD

**Issue by MgCI2** [wehaox/Typecho-Butterfly#56]
编辑页里预览主题报错（Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /www/wwwroot/typecho.mgcl2.ml/var/Widget/Base/Contents.php on line 938）
![image](https://user-images.githubusercontent.com/78311281/225800610-c0caa1ca-48eb-470c-9710-51dde7ebace2.png)

**Comment by wehaox** [comment]
非主题文件报错，无法定位错误，看看是不是插件冲突

**Comment by MgCI2** [comment]
已禁用掉全部插件，仍然报错
附图：
![image](https://user-images.githubusercontent.com/78311281/225945175-da937a0a-4e33-42cf-99db-3b199545e2ff.png)
![image](https://user-images.githubusercontent.com/78311281/225945320-5d507a7d-d896-4a92-96a3-d4067c170f9c.png)

**Comment by Dev-Wiki** [comment]
文章界面 也有这个错误 :

> Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /app/var/Widget/Base/Contents.php on line 938

https://blog.devwiki.net/2023/04/27/managed-cpp-unmanaged-cpp-standard-cpp.html
