### ISSUE TITLE
[Bug]: md渲染问题

### ISSUE THREAD

**Issue by Amarsimos** [wehaox/Typecho-Butterfly#58]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.5

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Chrome

### 博客的运行环境？ | What the running environment of the blog?

linux|php7.2+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

开发者您好，感谢您的辛勤付出使得typecho能拥有如此精美的主题，在使用过程中我也发现了一些问题，经过一番排查基本确定是该主题的存在的bug，即当使用md的图片链接功能（\!\[test.png\]\(https://www.example.com/test.png))  的同时，在下方同时使用标题语法（如###）会出现渲染错误，图片无法渲染并且图片之后的文字被渲染成标题。由于目前自己仅有一台设备，暂时无法在其它设备复现，希望开发者您能在百忙之中抽空检查一下，万分感谢您的付出！以下是问题截图：
下方无标题语法时：
![no#.png](https://kjimg10.360buyimg.com/ott/jfs/t20250408/213162/28/28131/258418/6432bd14F99224f80/3cc8e70214d20530.png)
![no#2.png](https://kjimg10.360buyimg.com/ott/jfs/t20250408/149525/8/31341/484259/6432bdb1F0953e254/b89e390ba2f94f71.png)
下方有标题语法时：
![#.png](https://kjimg10.360buyimg.com/ott/jfs/t20250408/165964/29/31413/260593/6432bd07Ff341185b/218c3a4dd9d51bf5.png)
![#2.png](https://kjimg10.360buyimg.com/ott/jfs/t20250408/99474/12/38187/556361/6432bd24Fa134614e/368a5ffac3f1cd0c.png)
有标题语法时的默认主题下显示正常：
![default.png](https://kjimg10.360buyimg.com/ott/jfs/t20250408/66824/34/26074/605462/6432bd14Fe2e03893/92381728e8f08804.png)

**Comment by wehaox** [comment]
新版本已发布，看看是否已解决，还不行需要你提供下md原文
