### ISSUE TITLE
当前在线人数 的bug

### ISSUE THREAD

**Issue by Yummy-cookie** [wehaox/Typecho-Butterfly#59]
Warning: fopen(usr/themes/butterfly/online.dat): failed to open stream: Permission denied in /biscuilt/biscuilt/blog/usr/themes/butterfly/functions.php on line 1562

Warning: flock() expects parameter 1 to be resource, bool given in /biscuilt/biscuilt/blog/usr/themes/butterfly/functions.php on line 1563

Warning: fputs() expects parameter 1 to be resource, bool given in /biscuilt/biscuilt/blog/usr/themes/butterfly/functions.php on line 1564

Warning: flock() expects parameter 1 to be resource, bool given in /biscuilt/biscuilt/blog/usr/themes/butterfly/functions.php on line 1565

Warning: fclose() expects parameter 1 to be resource, bool given in /biscuilt/biscuilt/blog/usr/themes/butterfly/functions.php on line 1566
1

**Comment by wehaox** [comment]
确保usr/themes/butterfly/online.dat有读写权限
