### ISSUE TITLE
手机端主页顶图无法自适应，显示不完整

### ISSUE THREAD

**Issue by linmiao233** [wehaox/Typecho-Butterfly#6]
手机端主页顶图无法自适应，显示不完整
另外询问下浏览器滑块颜色该在哪里修改 自定义主题颜色不起到作用
![22](https://user-images.githubusercontent.com/49273456/159160495-9533f44a-4ac9-4784-8d9b-25a64d261b20.png)

![111](https://user-images.githubusercontent.com/49273456/159160498-559496c1-1e83-42f2-b053-cb292cb425a4.png)

**Comment by XenWayne** [comment]
1.关于手机端顶图，你可以自行修改index.css 
在#page-header选择器 
修改background-position: center bottom;

2.关于浏览器滑块颜色，请修改custom.css
使用伪类选择器::-webkit-scrollbar-thumb
修改background-color即可。

**Comment by XenWayne** [comment]
不过话说回来（
滚动条颜色确实应该纳入到主题色的范围里 @wehaox

**Comment by vaettw** [comment]
> 我尝试了，但是无果。

**Comment by XenWayne** [comment]
> 我尝试了，但是无果。
清缓存了么（
