### ISSUE TITLE
[Bug]: 解析markdown "> xx" 异常

### ISSUE THREAD

**Issue by Dev-Wiki** [wehaox/Typecho-Butterfly#69]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.6

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Edge

### 博客的运行环境？ | What the running environment of the blog?

linux|php8.0+|typecho1.2|sqlite|nginx

### 问题描述 | Describe the bug

![image](https://github.com/wehaox/Typecho-Butterfly/assets/12946956/45156439-4d40-4511-8921-972eeb63c34f)

上图是 markdown原文, 下图是渲染的结果:

![image](https://github.com/wehaox/Typecho-Butterfly/assets/12946956/260c6432-195d-48b8-8c49-5c4ebc4bb905)

参见文章地址:

https://blog.devwiki.net/2023/05/17/good-tools-small-tools-2.html#cl-1

**Comment by Dev-Wiki** [comment]
由于显示异常 已经设置为别的主题, 如果需要演示 请添加我的微信:dev-wiki

**Comment by wehaox** [comment]
你指的是上面的字变小了，还是什么

**Comment by Dev-Wiki** [comment]
![image](https://github.com/wehaox/Typecho-Butterfly/assets/12946956/329617d5-62be-479e-a86a-e3488559d595)

解析引用时 会出现如上图的嵌套。。。

> 你指的是上面的字变小了，还是什么

**Comment by Dev-Wiki** [comment]
这是主题显示的完整效果：
![image](https://github.com/wehaox/Typecho-Butterfly/assets/12946956/326639b0-f394-4599-b839-6d7c9934328d)

这是切换别的主题 显示的效果：
![image](https://github.com/wehaox/Typecho-Butterfly/assets/12946956/8b7c686b-188e-4b88-9f18-cceb47fa7b6c)

**Comment by Dev-Wiki** [comment]
这个问题比较严重, 麻烦作者看下, 非常感谢~

**Comment by wehaox** [comment]
> 这个问题比较严重, 麻烦作者看下, 非常感谢~

现在没有太多精力放在主题上，我会尽快解决

**Comment by Dev-Wiki** [comment]
> > 这个问题比较严重, 麻烦作者看下, 非常感谢~
> 
> 现在没有太多精力放在主题上，我会尽快解决

非常感谢作者~

**Comment by wehaox** [comment]
我无法复现，可能需要你提供下文章

**Comment by Dev-Wiki** [comment]
> 

已发送, 博客已经切换为 本主题, 可以查看链接, 作者查看完成后 我再切换:

https://blog.devwiki.net/2023/05/17/good-tools-small-tools-2.html#cl-1

**Comment by wehaox** [comment]
> > 
> 
> 已发送, 博客已经切换为 本主题, 可以查看链接, 作者查看完成后 我再切换:
> 
> https://blog.devwiki.net/2023/05/17/good-tools-small-tools-2.html#cl-1

已复现，可以切换了

**Comment by Dev-Wiki** [comment]
> > 这么晚 作者大大辛苦了
> > 目前已定位问题，可以先将function.php里的1014行先注释，下版本会修复此问题

注释后已经正常 可点击上面的链接 查看效果

**Comment by wehaox** [comment]
新版本已发布
