### ISSUE TITLE
导航栏图标显示异常

### ISSUE THREAD

**Issue by vaettw** [wehaox/Typecho-Butterfly#7]
![image](https://user-images.githubusercontent.com/26769896/160224709-67f19bf3-0fb4-44da-9cde-a58da7a96366.png)
此处标签页展示图标显示异常，排查了一下问题，**好像是$this->title获取到的字符含有空格，换行等字符**。造成匹配不上。
![image](https://user-images.githubusercontent.com/26769896/160224761-0b2b7256-3b76-4dc9-820c-2d01b16d1117.png)
此图是我的博客显示问题，希望指点一下，暂时没有找到解决方案。

博客地址：yanjiuseng.top

**Comment by wehaox** [comment]
建议关闭自动生成导航栏，使用自定义导航栏，具体看：
https://blog.wehaox.com/archives/typecho-butterfly.html#cl-21

**Comment by wehaox** [comment]
用的是typecho1.2吗

**Comment by vaettw** [comment]
> 用的是typecho1.2吗

是的，之前一直用的是开发版1.2RC2，前天升级到了1.2，测试了一下，还是原来的情况。
![image](https://user-images.githubusercontent.com/26769896/161695991-e58128c1-233b-42de-9d2d-13bbecfdd639.png)

**Comment by wehaox** [comment]
已经知道问题了，下个版本修复，如果还有关于1.2使用中的问题再向我反馈

**Comment by vaettw** [comment]
好的，感谢您！

**Comment by wehaox** [comment]
1.4.4已修复此问题
