### ISSUE TITLE
归档页面中的文章封面设置无效

### ISSUE THREAD

**Issue by howardhey** [wehaox/Typecho-Butterfly#77]
如果在后台设置某些文章不显示封面，在首页的显示是没问题的，但是在归档页面中不生效，还是会显示默认封面，不能实现隐藏。如下：

![image](https://github.com/wehaox/Typecho-Butterfly/assets/126569075/06c03877-0b8b-4bf5-aab6-e8546867bdf7)

请问能否解决，谢谢，我自己不怎么懂php，但我去看这个页面模板好像确实没判断隐藏封面的问题。

我不清楚这是主题特性还是实现的时候忘记添加规则了，因此没有放入bug反馈，还请大佬解答。

**Comment by wehaox** [comment]
算是特性吧，显示的是无封面的默认图片，我之后想想怎么处理

**Comment by wehaox** [comment]
已更新
