### ISSUE TITLE
[Bug]: footer.php  第六行在首页 是无法获取到作者的。返回为null 

### ISSUE THREAD

**Issue by luckmao** [wehaox/Typecho-Butterfly#79]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.8

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Chrome

### 博客的运行环境？ | What the running environment of the blog?

linux|php7.2+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

      今天安装最新版 typecho 然后安装你的主题后
        <div class="copyright">©<?php echo date('Y'); ?> By <?php $this->author(); ?></div>
在首页这里  $this->author(); 返回为null 关于 可以返回值 。

**Comment by wehaox** [comment]
无法复现，你是否为多用户
