### ISSUE TITLE
请问支持typecho 1.2吗？

### ISSUE THREAD

**Issue by yu526** [wehaox/Typecho-Butterfly#8]
如题，不敢贸然升级typecho

**Comment by vaettw** [comment]
已升级，没问题。个人感觉typecho1.2变化不大。可能我之前用的是RC2的开发版。

**Comment by wehaox** [comment]
现已支持

**Comment by mylifeinn** [comment]
## 你好，我用1.2安装这个主题遇到两个问题？
1. 首页文章默认显示数量如何修改？
2. 文章代码块点击复制按钮无法复制代码到剪切板。
> 以上希望各位能帮忙看下，谢谢:-)
