### ISSUE TITLE
[Bug]: 评论区的用户名显示有问题

### ISSUE THREAD

**Issue by BFDZ** [wehaox/Typecho-Butterfly#80]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.8

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Edge

### 博客的运行环境？ | What the running environment of the blog?

linux|php7.2+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

我自己的名字和添加过自定义认证的名字，显示出来是这个样子，鼠标放上面还有一个代码出现
![Snipaste_2023-12-07_10-55-29](https://github.com/wehaox/Typecho-Butterfly/assets/12859302/9758a601-501a-4e0e-b251-b2bda455df7a)
![Snipaste_2023-12-07_10-57-33](https://github.com/wehaox/Typecho-Butterfly/assets/12859302/837bcc0d-8d77-48a7-aff4-f958bdc8e0ca)

出现问题的网页：https://slyw.me/2023/11/03/302/#cl-3
https://slyw.me/2022/11/12/201/comment-page-1#comment-54

**Comment by wehaox** [comment]
已复现，临时解决办法：
设置 > 评论 > 评论者名称显示时自动加上其个人主页链接
勾选去掉，下版本修复

**Comment by wehaox** [comment]
已修复
