### ISSUE TITLE
[Bug]: 网站fa图标的CDN链接存在跨域请求的问题

### ISSUE THREAD

**Issue by BFDZ** [wehaox/Typecho-Butterfly#82]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.8

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Edge

### 博客的运行环境？ | What the running environment of the blog?

linux|php7.2+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

网站更新主题以后，fa图标都不显示了，检查发现是图标文件的链接，因为跨域问题被浏览器阻止，这个问题怎么解决？
![Snipaste_2023-12-12_11-35-14](https://github.com/wehaox/Typecho-Butterfly/assets/12859302/f8bbccfc-0833-48cd-b6e0-aa3af41b0827)
![Snipaste_2023-12-12_11-35-38](https://github.com/wehaox/Typecho-Butterfly/assets/12859302/e64c6024-621b-4317-b5a3-596d9315d678)
![Snipaste_2023-12-12_11-36-07](https://github.com/wehaox/Typecho-Butterfly/assets/12859302/87f07e6f-72e1-4624-a8e3-ff7e0a806c11)

**Comment by wehaox** [comment]
header_com 51行 替换成 https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css

**Comment by wehaox** [comment]
staticfile已恢复
