### ISSUE TITLE
[Bug]: butterfly主题顶图在mobile safari上显示问题

### ISSUE THREAD

**Issue by Remelens** [wehaox/Typecho-Butterfly#85]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.6-fix

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Safari

### 博客的运行环境？ | What the running environment of the blog?

linux|php8.0+|typecho1.2|sqlite|nginx

### 问题描述 | Describe the bug

`index.css`:
```css
#page-header.full_page{height:100vh;background-attachment:fixed}
```
`background-attachment:fixed`和另一个参数（不记得是什么了）在我的mobile safari上混用就会像这样，只显示顶图**一小部分**
![IMG_8601.jpeg](https://img2.imgtp.com/2024/03/04/SRaAfTe0.jpeg)

本质上和 #61 是同一个问题，以及之前ios所有浏览器似乎都是同一个引擎

**Comment by wehaox** [comment]
这个问题在1.7.6应该是修复了，看下最新版本是否存在同样问题呢
