### ISSUE TITLE
[Bug&Feat]: 如何修改首页默认文章数量，文章代码块无法复制。

### ISSUE THREAD

**Issue by mylifeinn** [wehaox/Typecho-Butterfly#87]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.7.9

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Chrome

### 博客的运行环境？ | What the running environment of the blog?

linux|php7.2+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

1. 首页文章默认显示数量如何修改？
2. 文章代码块点击复制按钮无法复制代码到剪切板。
> 我使用的是docker容器版的typecho 1.2，以上希望各位能帮忙看下，谢谢:-)

**Comment by wehaox** [comment]
确认浏览器有复制权限和HTTPS

**Comment by mylifeinn** [comment]
我确定浏览器有复制权限，并且是https访问，但代码块依旧无法复制的

**Comment by wehaox** [comment]
是否有删文件
首页typecho里设置

**Comment by mylifeinn** [comment]
> 是否有删文件 首页typecho里设置
确实是没有删过文件，只不过typecho是用容器搭建的，然后mysql是在另一台服务器。
对php代码不熟悉，是在index.php修改下面这段代码吗？
```php
if($this->options->googleadsense != ""):
$i=1;
if($this->options->pageSize<=5)
{
    $k=$m=$g=3;
}else if($this->options->pageSize==10)
{
    $k=rand(3,4);
    $m=rand(6,8);
    $g=rand(10,12);
}else if($this->options->pageSize>5&&$this->options->pageSize<10){
    $k=$m=$g=4;
}
endif;
```

**Comment by wehaox** [comment]
我都说了typecho里的设置,不用改代码

**Comment by mylifeinn** [comment]
> 我都说了typecho里的设置,不用改代码

终于找到这个设置了，谢谢，之前一直在主题配置里找 - -'
复制代码块问题不知道咋解决，您可以试一下
[https://delistudio.top/](https://delistudio.top/)

**Comment by logce** [comment]
你的主题文件不完整，这个容器带主题是别人打包的吗

**Comment by wehaox** [comment]
你的主题文件不完整，这个容器带主题是别人打包的吗

**Comment by mylifeinn** [comment]
> 你的主题文件不完整，这个容器带主题是别人打包的吗

额，我在docker hub上检索typecho，用的是第一个，收藏和下载最多，刚细看了下确实不是官方的，排第二的才是官方的，汗。
[https://hub.docker.com/r/80x86/typecho](https://hub.docker.com/r/80x86/typecho)
BTW,虽然不是官方的，但这个容器并没有自带你这个butterfly主题。我是将你的主题文件手动放到theme文件夹来用的。
