### ISSUE TITLE
在打开的网站内点击首页，会报错“Uncaught ReferenceError: runtimeshow is not defined”

### ISSUE THREAD

**Issue by vaettw** [wehaox/Typecho-Butterfly#9]
如题，打开的网站中，点击关于后，再点首页后会在控制台一直疯狂报错。（站点地址：yanjiuseng.top）暂时打开pjax方便您在线查看错误、调试。
![image](https://user-images.githubusercontent.com/26769896/161739073-cd34d6bc-8eaf-48fe-a2a1-210c8f2d347a.png)
![image](https://user-images.githubusercontent.com/26769896/161739343-26547c8b-4382-4e73-9f52-e64ffdb9f847.png)

```
VM464:12 Uncaught ReferenceError: runtimeshow is not defined
    at show_date_time (<anonymous>:12:1)
    at <anonymous>:1:1
```
排查后是打开网站Pjax后才会报错，关闭后就正常了。经过搜索没有找到问题的原因。

如果是Pjax的原因，我去过作者您的网站，点击关于后再点击首页就没有此问题。不知道是不是我自己电脑的问题，麻烦您有空可以按照操作试一下，是否有同样的问题存在。

**Comment by wehaox** [comment]
因为主页侧栏的网站咨询中 已运行时间 是通过js处理的，pjax导致js丢失，开始疯狂报错，可以先将主页的网站咨询打开，下个版本我会换一种方式来修复此问题

**Comment by wehaox** [comment]
新版本已发布
