### ISSUE TITLE
[Bug]: 1.8版本文章阅读统计出错

### ISSUE THREAD

**Issue by shuiwudengli** [wehaox/Typecho-Butterfly#94]
### 是否从release页下的主题？ | Is the theme download from Release Page?

是 (Yes)

### 使用的 Butterfly 版本？ | What version of Butterfly are you use?

1.8

### 是否修改过主题文件？ | Has the theme files been modified?

不是 (No)

### 使用的浏览器？ | What browse are you using?

Chrome

### 博客的运行环境？ | What the running environment of the blog?

linux|php8.0+|typecho1.2|mysql5.6+|nginx

### 问题描述 | Describe the bug

![屏幕截图 2024-10-03 094446](https://github.com/user-attachments/assets/b31626e1-22f9-464d-a556-394ef5169e2f)
更新到1.8版本后，文章页面阅读统计出错，返回上一个版本恢复正常

**Comment by shuiwudengli** [comment]
> ### 是否从release页下的主题？ | Is the theme download from Release Page?
> 是否从release页下的主题？ |主题是从发布页面下载的吗？
> 是 (Yes)
> 
> ### 使用的 Butterfly 版本？ | What version of Butterfly are you use?
> 使用的 Butterfly 版本？ |您使用的 Butterfly 是什么版本？
> 1.8
> 
> ### 是否修改过主题文件？ | Has the theme files been modified?
> 不是 (No)
> 
> ### 使用的浏览器？ | What browse are you using?
> Chrome 铬
> 
> ### 博客的运行环境？ | What the running environment of the blog?
> 博客的运行环境？ |博客的运行环境如何？
> linux|php8.0+|typecho1.2|mysql5.6+|nginx
> 
> ### 问题描述 | Describe the bug
> ![屏幕截图 2024-10-03 094446](https://private-user-images.githubusercontent.com/96819893/373084040-b31626e1-22f9-464d-a556-394ef5169e2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjA0NDUsIm5iZiI6MTcyNzkyMDE0NSwicGF0aCI6Ii85NjgxOTg5My8zNzMwODQwNDAtYjMxNjI2ZTEtMjJmOS00NjRkLWE1NTYtMzk0ZWY1MTY5ZTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDAxNDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDVmOTNhYzkxZmE4MTYxMTNjMTkwYTQ0OGFjMDIzNDU3MDZjN2EwOGRmOTc1OTZmN2ZkYTUwNWFkMDZlMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vwYRRoZi-S0c8jDVg6FeS4wuWmIwJH6KBOzJMo_DPvI) 
更新到1.8版本后，文章页面阅读统计出错，返回上一个版本恢复正常

**Comment by wehaox** [comment]
已修复 [1.8.0_fix](https://github.com/wehaox/Typecho-Butterfly/commit/1f88d2278a5ab343c1f27e7f091ec71e29ef989d)
